name: CI

on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
        deno-version: v1.x
      - name: Check Formatting
        run: deno fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
        deno-version: v1.x
      - name: Lint
        run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
        deno-version: v1.x
      - name: Run tests
        run: deno test --allow-read --unstable
